### ISSUE TITLE
action doesn't work on functions with arguments

### ISSUE THREAD

**Issue by belka-ew** [funkwerk/dmocks#2]
This code should fail, but it doesn't:
```d
class B
{
    void foo(string[] = null)
    {
    }
}

unittest
{
    auto mocker = new Mocker;
    auto klass = mocker.mock!B;

    mocker.expect(klass.foo).action({ assert(false); });

    mocker.replay;

    klass.foo;

    mocker.verify;
}
```

```d
mocker.expect(klass.foo).action((string[] = null) { assert(false); });
```
works as expected.
```d
mocker.expect(klass.foo).action(delegate void(string[] = null) { assert(false); });
```
works as expected.

```d
    mocker.expect(klass.foo(null)).action((string[]) => { assert(false); });
```
doesn't fail.

Event if the passed callback has wrong signature, caller should be notified (with an exception according to the function documentation).

**Comment by thinkingerrol** [comment]
I've tested with dmocks 2.0.6 and this issue can IMHO be closed. For the above example I got a helpful error message at compile-time: `object.Error@(0): cannot call action: type void delegate() does not match argument type (string[])`
